pipeline {
  agent any

  stages {
    stage('Build') {
      steps {
        sh 'docker build --no-cache -t check_status .' // Added --no-cache for clean builds
      }
    }

    stage('Run') {
      steps {
        sh 'docker run --rm -it check_status https://www.google.com/' // Added --rm to remove container after run
      }
    }
  }
}
