name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Use latest version

      - name: Set up Python
        uses: actions/setup-python@v4  # Use newer version
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Discover Python projects with setup.py
        id: discover
        run: |
          echo "projects=$(find . -type f -name 'setup.py' -exec dirname {} \; | paste -sd ' ' -)" >> $GITHUB_OUTPUT

      - name: Run tests
        run: |
          for project in ${{ steps.discover.outputs.projects }}; do
            echo "Testing $project"
            cd "$project"
            pytest || exit 1
            cd - > /dev/null
          done
